# Generated by Django 6.0.5 on 2026-05-26 04:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fuel', 'Fuel Combustion'), ('electricity', 'Purchased Electricity'), ('flight', 'Air Travel'), ('hotel', 'Hotel Stay'), ('car', 'Car / Ground Transport')], max_length=20)),
                ('substance', models.CharField(help_text='e.g. diesel, natural_gas, grid_IN', max_length=100)),
                ('unit', models.CharField(help_text='e.g. liter, kWh, pkm, room-night', max_length=20)),
                ('kg_co2e', models.FloatField(help_text='kg CO2e per unit')),
                ('source', models.CharField(help_text='e.g. IPCC AR6, DEFRA 2023, EPA AP-42', max_length=200)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, help_text='NULL = currently active', null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'substance', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP – Fuel & Combustion'), ('utility_electricity', 'Utility – Electricity'), ('travel_flights', 'Travel – Flights'), ('travel_hotels', 'Travel – Hotels'), ('travel_ground', 'Travel – Ground Transport')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Queued'), ('processing', 'Processing'), ('success', 'Success'), ('partial', 'Partial – Some Errors'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='raw/%Y/%m/')),
                ('source_checksum', models.CharField(blank=True, help_text='SHA-256 of raw bytes — used for duplicate detection', max_length=64)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('flagged_rows', models.PositiveIntegerField(default=0)),
                ('processing_log', models.JSONField(default=list)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ingestion_params', models.JSONField(default=dict)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='core.tenant')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('1', 'Scope 1 – Direct'), ('2', 'Scope 2 – Indirect Energy'), ('3', 'Scope 3 – Value Chain')], max_length=1)),
                ('category', models.CharField(help_text='e.g. Stationary Combustion, Purchased Electricity, Business Air Travel', max_length=120)),
                ('source_type', models.CharField(max_length=30)),
                ('raw_quantity', models.FloatField(blank=True, null=True)),
                ('raw_unit', models.CharField(blank=True, max_length=50)),
                ('raw_description', models.CharField(blank=True, max_length=500)),
                ('raw_period', models.CharField(blank=True, max_length=100)),
                ('quantity_norm', models.FloatField(blank=True, help_text='In SI base unit (liters / kWh / kg / km / room-nights)', null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=30)),
                ('conversion_applied', models.CharField(blank=True, help_text='Human-readable conversion, e.g. "1 GAL = 3.785 L"', max_length=200)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('plant_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('cost_center', models.CharField(blank=True, max_length=50)),
                ('emission_factor', models.FloatField(blank=True, null=True)),
                ('emission_factor_unit', models.CharField(blank=True, help_text='e.g. kg CO2e/liter', max_length=50)),
                ('emission_factor_source', models.CharField(blank=True, max_length=200)),
                ('co2e_kg', models.FloatField(blank=True, help_text='kg CO2 equivalent — always kilograms, never tonnes', null=True)),
                ('source_row_ref', models.CharField(blank=True, help_text='Row number in source file (1-indexed)', max_length=50)),
                ('raw_data_snapshot', models.JSONField(default=dict, help_text='Full source row as received — immutable')),
                ('source_specific', models.JSONField(default=dict, help_text='Source-type fields: fuel_type, meter_id, cabin_class, etc.')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for Audit')], default='pending_review', max_length=20)),
                ('flag_codes', models.JSONField(default=list, help_text='List of FLAG_* codes — queryable, not free text')),
                ('flag_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edit_history', models.JSONField(default=list, help_text='Append-only: [{user, ts, field, old, new}]')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.ingestionbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='core.tenant')),
            ],
            options={
                'ordering': ['-activity_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='analyst', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlantCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('grid_region', models.CharField(blank=True, help_text='Grid emission factor region code (e.g. IN, DE, US)', max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_codes', to='core.tenant')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['tenant', 'source_type'], name='core_ingest_tenant__7c9a8e_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['tenant', '-uploaded_at'], name='core_ingest_tenant__6d13eb_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'scope', 'status'], name='core_emissi_tenant__27cd85_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'source_type', 'status'], name='core_emissi_tenant__8113be_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'activity_date'], name='core_emissi_tenant__a3fb9f_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['batch', 'status'], name='core_emissi_batch_i_288f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'co2e_kg'], name='core_emissi_tenant__efab7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantmembership',
            unique_together={('user', 'tenant')},
        ),
    ]
